### ISSUE TITLE
IPv6 enabled by default

### ISSUE THREAD

**Issue by Npok** [openconfig/public#227]
There is a problem with the ipv6 enable by default in some specific cases:

[Link to the if-ip model](https://github.com/openconfig/public/blob/master/release/models/interfaces/openconfig-if-ip.yang#L443)
```
[...]
  grouping ipv6-global-config {
    description
      "Configuration data at the global level for each
      IPv6 interface";

    leaf enabled {
      type boolean;
      default true;
      description
        "Controls whether IPv6 is enabled or disabled on this
        interface.  When IPv6 is enabled, this interface is
        connected to an IPv6 stack, and the interface can send
        and receive IPv6 packets.";
}
[...]
```

To replicate the problem, we create a Port-Channel with a subif and a VRF:
```
<config> 
    <interfaces xmlns="http://openconfig.net/yang/interfaces"> 
        <interface>
            <name>Port-Channel1</name> 
            <config> 
                <name>Port-Channel1</name> 
            </config>
        </interface> 
    </interfaces>
</config> 

<config> 
    <interfaces xmlns="http://openconfig.net/yang/interfaces"> 
        <interface>
            <name>Port-Channel1</name> 
            <config> 
                <name>Port-Channel1</name>  
            </config>
            <subinterfaces>
                <subinterface> 
                    <index>20</index>
                    <config> 
                        <index>20</index>
                    </config>
                </subinterface>
            </subinterfaces> 
        </interface> 
    </interfaces>
</config>

router-200-1(config)#vrf definition TestVRF
```

We have the IPv6 enable as defined in the model:
```
router-200-1: sh run
vrf definition TestVRF
interface Port-Channel1
!
interface Port-Channel1.20
   ipv6 enable
!
```

But when we want to specify the VRF for the interface, there is an error:
```
<config> 
    <network-instances xmlns="http://openconfig.net/yang/network-instance">
        <network-instance> 
            <name>TestVRF</name>
                <config> 
                    <name>TestVRF</name>
                </config>
            <interfaces> 
                <interface>
                    <id>Port-Channel1.20</id>
                    <config> 
                        <id>Port-Channel1.20</id>
                    </config>
                </interface> 
            </interfaces>
        </network-instance>
    </network-instances> 
</config>

Traceback (most recent call last):
  File "edit_config.py", line 31, in <module>
    config=conf, default_operation="merge", target="running"
  File "/home/ubuntu/src/.venv/lib/python3.5/site-packages/ncclient/manager.py", line 216, in execute
    raise_mode=self._raise_mode).request(*args, **kwds)
  File "/home/ubuntu/src/.venv/lib/python3.5/site-packages/ncclient/operations/edit.py", line 67, in request
    return self._request(node)
  File "/home/ubuntu/src/.venv/lib/python3.5/site-packages/ncclient/operations/rpc.py", line 341, in _request
    raise self._reply.error
ncclient.operations.rpc.RPCError: interface Port-Channel1.20 cannot be in multiple network-instances
```

The only way to prevent this is to disable manually, or with another call, the IPv6 on the Port-Channel1.20.

I don't know if this is intended, if there is a good reason to have it enabled by default.

**Comment by aashaikh** [comment]
I'm not sure how this problem relates to enabling IPv6 on the interface.  The error message you posted seems to indicate that you've placed the same interface in multiple network instances, not that the interface has IPv6 enabled.

**Comment by Npok** [comment]
It is, but the only way we found to not "lock" the interface into the DEFAULT network-instance, is to disable any configuration that is related to the interface.

```
router-200-1#sh ver
 cEOSLab
Software image version: 4.21.4F
Internal build version: 4.21.4F-11469004.4214F

router-200-1(config)#int port-Channel 1
router-200-1(config-if-Po1)#int port-Channel 1.20
router-200-1(config-if-Po1.20)#sh run | section Port-Channel
interface Port-Channel1
!
interface Port-Channel1.20
!
```

And the following payload, works fine:
```
<config> 
    <network-instances xmlns="http://openconfig.net/yang/network-instance">
        <network-instance> 
            <name>TestVRF</name>
                <config> 
                    <name>TestVRF</name>
                </config>
            <interfaces> 
                <interface>
                    <id>Port-Channel1.20</id>
                    <config> 
                        <id>Port-Channel1.20</id>
                    </config>
                </interface> 
            </interfaces>
        </network-instance>
    </network-instances> 
</config>

<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:82fe2b61-15bc-460b-9f08-a15ac7cca137">
  <ok/>
</rpc-reply>
```

If I use OpenConfig model, the creation of the SubInterface enables IPv6 by default, let's replicate this manually:
```
router-200-1(config)#int port-Channel 1
router-200-1(config-if-Po1)#int port-Channel 1.20
router-200-1(config-if-Po1.20)#ipv6 enable
router-200-1(config-if-Po1.20)#sh run | section Port-Channel
interface Port-Channel1
!
interface Port-Channel1.20
   ipv6 enable
!
```

And then the exact same payload cannot be run properly:
```
<config> 
    <network-instances xmlns="http://openconfig.net/yang/network-instance">
        <network-instance> 
            <name>TestVRF</name>
                <config> 
                    <name>TestVRF</name>
                </config>
            <interfaces> 
                <interface>
                    <id>Port-Channel1.20</id>
                    <config> 
                        <id>Port-Channel1.20</id>
                    </config>
                </interface> 
            </interfaces>
        </network-instance>
    </network-instances> 
</config>

Traceback (most recent call last):
  File "edit_config.py", line 31, in <module>
    config=conf, default_operation="merge", target="running"
  File "/home/ubuntu/src/npa_poc_conf_gen/.venv2/lib/python3.6/site-packages/ncclient/manager.py", line 216, in execute
    raise_mode=self._raise_mode).request(*args, **kwds)
  File "/home/ubuntu/src/npa_poc_conf_gen/.venv2/lib/python3.6/site-packages/ncclient/operations/edit.py", line 67, in request
    return self._request(node)
  File "/home/ubuntu/src/npa_poc_conf_gen/.venv2/lib/python3.6/site-packages/ncclient/operations/rpc.py", line 341, in _request
    raise self._reply.error
ncclient.operations.rpc.RPCError: interface Port-Channel1.20 cannot be in multiple network-instances
```

So it's not directly related to the network-instance as the error message said, but more on the weird behavior with the configuration on an interface.
